[package]
name = "rust-wgpu-present-lag"
version = "0.1.0"
edition = "2021"
resolver="2"

[dependencies]
bytemuck = { version = "1.4", features = [ "derive" ] }
env_logger = "0.9.0"
image = "0.23.14"
imageproc = "0.22.0"
log = "0.4.14"
pollster = "0.2.4"
wgpu = "0.11.0"
winit = "0.25.0"